# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano//zmk
#     shield: reviung41
#
---
include:
  - board: nice_nano//zmk
    shield: cradio_left nicehatharry nice_view
  - board: nice_nano//zmk
    shield: cradio_right nicehatharry nice_view
  - board: nice_nano//zmk
    shield: phantom_left nicehatharry nice_view
  - board: nice_nano//zmk
    shield: phantom_right nicehatharry nice_view
  - board: xiao_rp2040//zmk
    shield: hummingbird
  - board: xiao_ble//zmk
    shield: hummingbird rgbled_adapter
  - board: xiao_ble//zmk
    shield: teenspirit rgbled_adapter
  - board: nice_nano//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: settings_reset
  - board: nice_nano//zmk
    shield: berylline_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: berylline_left_dongle
  - board: nice_nano//zmk
    shield: berylline_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: berylline_right_dongle
  - board: xiao_ble//zmk
    shield: berylline_dongle prospector_adapter
  - board: nice_nano//zmk
    shield: berylline_left
    artifact-name: berylline_left_standalone
  - board: nice_nano//zmk
    shield: berylline_right
    artifact-name: berylline_right_standalone

