CONFIG_ZMK_KEYBOARD_NAME="Rufous Wired"
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_MOUSE_DEFAULT_MOVE_VAL=1500
CONFIG_ZMK_MOUSE_DEFAULT_SCRL_VAL=20
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# CONFIG_RGBLED_WIDGET_INTERVAL_MS=250
# CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=50
# CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
